# Generated by Django 4.2.23 on 2025-10-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0006_result_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='maxVal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='minVal',
            field=models.IntegerField(default=0),
        ),
    ]
