# Generated by Django 4.2.26 on 2026-01-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0007_category_maxval_category_minval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('categories', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
    ]
