# Generated by Django 4.2.28 on 2026-03-16 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0008_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuscherColor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LuscherPositionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_group', models.CharField(choices=[('goal', 'Goal (1-2)'), ('state', 'State (3-4)'), ('suppressed', 'Suppressed (5-6)'), ('stress', 'Stress (7-8)')], max_length=20)),
                ('result_text', models.TextField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.luschercolor')),
            ],
        ),
        migrations.CreateModel(
            name='LuscherMainPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_text', models.TextField()),
                ('first_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_pairs', to='test.luschercolor')),
                ('second_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_pairs', to='test.luschercolor')),
            ],
        ),
        migrations.CreateModel(
            name='LuscherConflictRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_text', models.TextField()),
                ('color_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_a', to='test.luschercolor')),
                ('color_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_b', to='test.luschercolor')),
            ],
        ),
    ]
