# Generated by Django 4.2.28 on 2026-03-22 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0009_luschercolor_luscherpositionrule_luschermainpair_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('school', 'Школьник'), ('student', 'Студент'), ('worker', 'Работающий')], max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('education_direction', models.CharField(blank=True, choices=[('science', 'Естественные науки'), ('social', 'Социальные науки'), ('humanities', 'Гуманитарные науки'), ('technical', 'Технические'), ('economics', 'Экономика')], max_length=50, null=True)),
                ('work_direction', models.CharField(blank=True, choices=[('science', 'Естественные науки'), ('social', 'Социальные науки'), ('humanities', 'Гуманитарные науки'), ('technical', 'Технические'), ('economics', 'Экономика')], max_length=50, null=True)),
                ('avg_score', models.FloatField(blank=True, null=True)),
                ('result_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.test')),
            ],
        ),
    ]
